### PR TITLE
Do tag user results so we can reproduce tests

### PR DESCRIPTION
**Pull request by maurolepore**
If I understand correctly, the tests we run inside the
container are specific to data in user_results/. If so, 
should we tag user_results/? That way we can easily
reproduce the tests we run in any build.

I see there a benefit of tagging user_results. What
would be the downside?
﻿

### CODE REVIEW

**Comment by cjyetman** [comment]
I guess no real downside. Doesn't hurt anything.

I would imagine that at some point in the near-ish future, the user_reports repo will or should be deleted, after which we will have to adapt some of this code so that it doesn't break on it.

**Review by maurolepore — COMMENTED** [review]
If `$user_results` is unavailable (can't be cloned because of whatever reason)
the output is this:

```bash
# ... more

Unzipping pacta_web_template.zip ...

Cloning into 'FIXME'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Saving 2dii_pacta into pacta_web/2dii_pacta.tar.gz ...
﻿
# ... more
```

Note that the output shows the error but the script continues.

--

Else, the output is this:

```bash
# ... more

Unzipping pacta_web_template.zip ...

Cloning into 'user_results'...
remote: Enumerating objects: 71, done.
remote: Counting objects: 100% (71/71), done.
remote: Compressing objects: 100% (57/57), done.
remote: Total 71 (delta 23), reused 55 (delta 14), pack-reused 0
Receiving objects: 100% (71/71), 5.38 MiB | 5.39 MiB/s, done.
Resolving deltas: 100% (23/23), done.

Saving 2dii_pacta into pacta_web/2dii_pacta.tar.gz ...

# ... more
```

**Comment by cjyetman** [comment]
actually, sorry I know this is a bit of a run around...

I now think probably the absolute best thing to do is to separate the code that builds the docker image and the code that wraps that up into a package with example files. The example files/scripts, and the example data like the user_results is not really a necessary part of the process, and once our web server admins have a clear understanding of how it works (hopefully by now already), it's probably silly to keep sending these example files.

sorry it's taken me a while to see/realize that

**Comment by maurolepore** [comment]
Great! Happy to make this script smaller and more focused. I'll submit my interpretation of your comment in a separate PR

**Pull request closed without merging**
